name: skool_reg
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.19.4 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    flutter_native_splash:
    flutter_launcher_icons: ^0.11.0
    cupertino_icons: ^1.0.2
    flutter_spinkit: ^5.1.0
    animations: ^2.0.7
    flutter_svg:
    syncfusion_flutter_sliders: ^20.4.51
    http: ^0.13.5
    google_fonts: ^4.0.3
    file_picker: ^5.2.5
    shared_preferences: ^2.0.18
    flutter_bloc:
    internet_connection_checker: ^1.0.0+1
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true
# splash screen
flutter_native_splash:

    color: "#42a5f5"
    image: assets/splash.png

    web: true
    # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
    web_image_mode: center

    # android_screen_orientation: sensorLandscape
    fullscreen: true

# end of splash logic

# app icon logic
flutter_icons:
  web:
    generate: true
    image_path: assets/Icon-01.png
  windows:
    generate: true
    image_path: assets/Icon-01.png
    icon_size: 48 # min:48, max:256, default: 48

    flutter_lints: ^2.0.0

    # To add assets to your application, add an assets section, like this:
    assets:
       - assets/
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages